name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/go-runc
          fetch-depth: 25

      - uses: samuelkarp/containerd-project-checks@go-install
        with:
          working-directory: src/github.com/containerd/go-runc

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/go-runc

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          working-directory: src/github.com/containerd/go-runc
          args: --timeout=5m
          skip-go-installation: true

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/go-runc

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
          bash <(curl -s https://codecov.io/bash)
        working-directory: src/github.com/containerd/go-runc
